version: '3'

services:
  backend-1:
      build: .
      container_name: flask_app
      restart: always
      working_dir: /app
      ports:
        - "8000:8000"
      volumes:
        - /home/backend-3/backend1:/app
      command: ["gunicorn", "-b", "0.0.0.0:8000", "server:app"]
      networks:
        - neocode
        
        
networks:
  neocode: