version: '3'
services:
  frontend:
    image: node:latest
    container_name: front
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/frontend:/app
    command: ["sh", "-c", "npm install && npm run build && npm run start"]
    networks:
      - neocode

networks:
  neocode:
