services:
  backend-2:
    image: node:latest
    container_name: backend2
    restart: always
    working_dir: /app
    ports:
      - "5000:5230"
    volumes:
      - /home/backend-3/backend2:/app
    command: ["sh", "-c", "npm install && npm run dev"]
    networks:
      - neocode

networks:
  neocode: