image: node:16

clone:
  depth: full

pipelines:
  default:
    - step:
        name: Executar Deploy
        script:
          - apt-get update && apt-get install -y sshpass
          - sleep 10s
          - sshpass -p $VM_PASSWORD ssh $VM_USER@$VM_HOST "cd backend3 && git pull origin main"


definitions:
  services:
    neocode-db:
      image: mysql:5.7
      variables:
        MYSQL_DATABASE: 'neocode'
        MYSQL_ROOT_PASSWORD: '102030@@'